server:
  port: 8800
  address: 0.0.0.0

nacos:
  config:
    server-addr: ehlxm.nacos.duowan.com:6801
    namespace: local
    bootstrap:
      enable: true
      log-enable: false
    type: yaml
    data-id:  ysoul-example-defaul
    group: openapi


spring:
  dynamic:
    thread-pool:
      enable: true  # 是否开启动态线程池
      banner: true  # 是否打印 banner
      collect: true  # 是否开启线程池数据采集，对接 Prometheus
      notify-platforms: # 通知报警平台，⚠️ 请替换为自己创建的群机器人
        - platform: 'WECHAT'  # 企业微信
          token: f4c7f861-d357-4567-9dbe-f33de503fb16
      nacos: # nacos apollo 任选其一
        data-id: soul-example-dynamic-hippo4j
        group: openapi
      config-file-type: yml  # 配置中心文件格式
      tomcat: # 三种容器线程池，任选其一
        core-pool-size: 100
        maximum-pool-size: 200
        keep-alive-time: 1000
      # 全局通知配置
      alarm: true  # 是否报警
      check-state-interval: 3000  # 检查线程池状态，是否达到报警条件，单位毫秒
      active-alarm: 80  # 活跃度报警阈值；假设线程池最大线程数 10，当线程数达到 8 发起报警
      capacity-alarm: 80  # 容量报警阈值；假设阻塞队列容量 100，当容量达到 80 发起报警
      alarm-interval: 8  # 报警间隔，同一线程池下同一报警纬度，在 interval 时间内只会报警一次，单位秒
      receive: xxx # 企业微信填写用户 ID（填写其它将无法达到 @ 效果）、钉钉填手机号、飞书填 ou_ 开头唯一 ID
      # 线程池配置
      executors:
        - thread-pool-id: 'message-consume'  # 线程池标识
          core-pool-size: 1  # 核心线程数
          maximum-pool-size: 1  # 最大线程数
          queue-capacity: 1  # 阻塞队列大小
          execute-time-out: 1000  # 执行超时时间，超过此时间发起报警
          blocking-queue: 'LinkedBlockingQueue'  # 阻塞队列名称，参考 QueueTypeEnum，支持 SPI
          rejected-handler: 'AbortPolicy'  # 拒绝策略名称，参考 RejectedPolicies，支持 SPI
          keep-alive-time: 1024  # 线程存活时间，单位秒
          allow-core-thread-time-out: true  # 是否允许核心线程超时
          thread-name-prefix: 'message-consume'  # 线程名称前缀
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  application:
    name: example


